### ISSUE TITLE
arubaoss_config unable to retrieve current config

### ISSUE THREAD

**Issue by brasswood** [aruba/aruba-ansible-modules#109]
ansible version: 2.9
python version: 2.7

I am getting this error when running arubaoss_config sometimes. The stderror message is `"Unable to decode JSON from response to exec_command(show running-config). Received 'None'."` I only get this error sometimes, and I don't know how to consistently reproduce it. It seems like running a different playbook or using a different inventory fixes it for a while. I am wondering if this is an issue with the underlying ansible ssh connection.

**Comment by brasswood** [comment]
Also, I was using cf683d6, I'll try using the latest commit.

**Comment by tchiapuziowong** [comment]
Hi @brasswood ! I noticed you're using the arubaoss_config module to execute the `show running-config` command, instead you should use the arubaoss_command module. That's the module you should use for show commands and any other CLI command that you wouldn't execute in the config context.

Try that and let me know if you have any further issues!

**Comment by brasswood** [comment]
I'm not explicitly running `show running-config`, the module does it automatically to determine the diff when `saved_when == 'modified'`.

**Comment by castjorge** [comment]
Hi @brasswood, Can you please share the  playbook you are using?

**Comment by brasswood** [comment]
Hi @castjorge,
``yml
---
- hosts: all
  gather_facts: no
  tasks:
    - arubaoss_config:
        lines:
          - interface 1/10 name "andrew was here"
          - interface 1/11 name "{{ my_custom_variable }}"
        save_when: modified
```

**Comment by brasswood** [comment]
@castjorge I am using the correct credentials, but I don't pass them in through inventory. Instead I pass credentials through `-u` and `-k` options on the command line. It has worked sometimes and hasn't worked other times.

**Comment by tchiapuziowong** [comment]
Hi @brasswood !
After much investigation we were unable to reproduce the issue, besides using incorrect credentials. If you could provide additional information on how to produce the issue seen we could look further into troubleshooting this?

**Comment by brasswood** [comment]
@tchiapuziowong Thank you for taking the time, I will investigate some more on my own.

**Comment by NeverUsedID** [comment]
HI, 
I have the same problem with save_when_ modified. Its a Aruba 2530 Switch without REST API enabled.

a simple: 

```
   - name: save running to startup when modified
       arubaoss_config:
         lines:
          - no telnet-server
        save_when: modified
```

returns: 

`FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "unable to retrieve current config", "stderr": "Unable to decode JSON from response to exec_command(show running-config). Received 'None'.", "stderr_lines": ["Unable to decode JSON from response to exec_command(show running-config). Received 'None'."]}
`

a save_when: modified ONLY, like the following:
```

  - name: save running to startup when modified
       arubaoss_config:
        save_when: modified

```

 returns: 

`
FAILED! => {"changed": false, "msg": "Request failed: <urlopen error [Errno -3] Temporary failure in name resolution>", "status": -1, "url": "http://None:80/rest/v6.0/login-sessions"}
`

even i have configured "network__cli". USername and password is correct, as long as iam not using save_wehen, everything is working.

**Comment by alagoutte** [comment]
Hi,

it is you replace on the return the address by None ?

REST is enable on the switch ? (and web-server with HTTP too ?), it is need by ansible

**Comment by tchiapuziowong** [comment]
Hi @NeverUsedID - just to make sure your ansible_connection variable is set to network_cli > just a single underscore correct?

**Comment by NeverUsedID** [comment]
Thank for you for your fast responses!

> it is you replace on the return the address by None ?

no.
 
> REST is enable on the switch ? (and web-server with HTTP too ?), it is need by ansible

No, its not. I thought, that its possible to choose between cli and RESTAPI. So for Arubaoss_config BOTH is required?

Hi @NeverUsedID - just to make sure your ansible_connection variable is set to network_cli > just a single underscore correct?

Yes,

```
ansible_connection=network_cli
ansible_network_os=arubanetworks.aos_switch.arubaoss

```
All commands are working just fine, only "save_when" is not working.

**Comment by NeverUsedID** [comment]
Update on that: i reinstalled it from git instead of using galaxy verison. Now it look a bit better, as the host and the provider are not null anymore. Still he tries to connect to the rest api, even i want to use cli. So is REST a MUST HAVE, even ì only want to use CLI commands?

Hosts file:

`
[arubatest]
192.x.x.x

[arubatest:vars]
ansible_ssh_user=cattools
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
ansible_connection=network_cli
ansible_network_os=arubaoss
ansible_user=remote-user

`

Command:

`ansible-playbook network/aruba_audit.yml --ask-pass -vvv
`

Complete output:

`

ansible-playbook 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Apr 15 2020, 17:07:12) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file
SSH password:
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin

PLAYBOOK: aruba_audit.yml *********************************************************************************************************************************************************************************************************************************************************
1 plays in network/aruba_audit.yml

PLAY [arubatest] ******************************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [save running to startup when modified] **************************************************************************************************************************************************************************************************************************************
task path: /home/ansible/playbooks/network/aruba_audit.yml:8
<192.x.x.x> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<192.x.x.x> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-local-3683VOGk6g `"&& mkdir /home/ansible/.ansible/tmp/ansible-local-3683VOGk6g/ansible-tmp-1593594404.96-3689-226910292485446 && echo ansible-tmp-1593594404.96-3689-226910292485446="` echo /home/ansible/.ansible/tmp/ansible-local-3683VOGk6g/ansible-tmp-1593594404.96-3689-226910292485446 `" ) && sleep 0'
<192.x.x.x> Attempting python interpreter discovery
<192.x.x.x> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<192.x.x.x> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/arubaoss/arubaoss_config.py
<192.x.x.x> PUT /home/ansible/.ansible/tmp/ansible-local-3683VOGk6g/tmplBHoyn TO /home/ansible/.ansible/tmp/ansible-local-3683VOGk6g/ansible-tmp-1593594404.96-3689-226910292485446/AnsiballZ_arubaoss_config.py
<192.x.x.x> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-local-3683VOGk6g/ansible-tmp-1593594404.96-3689-226910292485446/ /home/ansible/.ansible/tmp/ansible-local-3683VOGk6g/ansible-tmp-1593594404.96-3689-226910292485446/AnsiballZ_arubaoss_config.py && sleep 0'
<192.x.x.x> EXEC /bin/sh -c '/usr/bin/python /home/ansible/.ansible/tmp/ansible-local-3683VOGk6g/ansible-tmp-1593594404.96-3689-226910292485446/AnsiballZ_arubaoss_config.py && sleep 0'
<192.x.x.x> EXEC /bin/sh -c 'rm -f -r /home/ansible/.ansible/tmp/ansible-local-3683VOGk6g/ansible-tmp-1593594404.96-3689-226910292485446/ > /dev/null 2>&1 && sleep 0'
[DEPRECATION WARNING]: Distribution Ubuntu 16.04 on host 192.x.x.x should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this
host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [192.x.x.x]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "after": null,
            "api_version": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "diff_against": null,
            "diff_ignore_lines": null,
            "host": "192.x.x.x",
            "intended_config": null,
            "lines": null,
            "match": "line",
            "parents": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 80,
            "provider": {
                "api_version": null,
                "host": "192.x.x.x",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 80,
                "ssh_keyfile": null,
                "timeout": 30,
                "transport": "aossapi",
                "use_proxy": false,
                "use_ssl": false,
                "username": "remote-user",
                "validate_certs": false
            },
            "replace": "line",
            "running_config": null,
            "save_when": "always",
            "src": null,
            "ssh_keyfile": null,
            "timeout": 30,
            "use_ssl": false,
            "username": "remote-user",
            "validate_certs": false
        }
    },
    "msg": "Request failed: <urlopen error timed out>",
    "status": -1,
    "url": "http://192.x.x.x:80/rest/v6.0/login-sessions"
}

PLAY RECAP ************************************************************************************************************************************************************************************************************************************************************************
192.x.x.x               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
`

**Comment by tchiapuziowong** [comment]
Hi @NeverUsedID !

Thank you for the info! We're working on re-producing and troubleshooting the issue now! Reopening the issue and will update soon

**Comment by tchiapuziowong** [comment]
Hi @NeverUsedID  @brasswood ! We've uploaded a fix for this behavior - please pull, reinstall and validate the issue is resolved :) Also if you're running Ansible version 2.9+ I would suggest installing our[ Ansible collection ](https://galaxy.ansible.com/arubanetworks/aos_switch) and using that instead! 

https://github.com/aruba/aruba-ansible-modules/commit/33637dfe3a8dc406b7284de311ff706c25024db9

**Comment by NeverUsedID** [comment]
Thank you very much. Now its working! 

But there is still a problem: the tasks are always returning "changed".

Examples: 

```
    - name: save running config
      arubaoss_config:
        save_when: modified

    - name: enable snmp-community somecom
      arubaoss_config:
        lines:
          - snmp-server community somecom

    - name: save running config
      arubaoss_config:
        save_when: modified
```

If I run this Playbook a second time, all 3 tasks returning "changed", even the snmp community is aleady there.



-vvv output:

```
changed: [172.29.xx.xx] => {
    "changed": true,
    "commands": [
        "snmp-server community somecom"
    ],
    "invocation": {
        "module_args": {
            "after": null,
            "api_version": "None",
            "backup": false,
            "backup_options": null,
            "before": null,
            "diff_against": null,
            "diff_ignore_lines": null,
            "host": null,
            "intended_config": null,
            "lines": [
                "snmp-server community somecom"
            ],
            "match": "line",
            "parents": null,
            "password": null,
            "port": null,
            "provider": {
                "api_version": null,
                "host": "172.29.xx.xx",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 80,
                "ssh_keyfile": null,
                "timeout": 30,
                "transport": "aossapi",
                "use_proxy": false,
                "use_ssl": false,
                "username": "myuser",
                "validate_certs": false
            },
            "replace": "line",
            "running_config": null,
            "save_when": "never",
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": false
        }
    },
    "updates": [
        "snmp-server community somecom"
    ]
}

```
